pipeline {
  agent { label 'jenkins-Agent' }
  tools {
    jdk 'Java17'
    maven 'Maven3'
  }
  stages{
    stage("Cleanup Workspace"){
                steps {
                cleanWs()
                }
        }

        stage("Checkout from SCM"){
                steps {
                    git branch: 'master', credentialsId: 'github', url: 'https://github.com/abhishek5254/NoteTaker/tree/9b63a3878f06d6a640dedb4513779e3d81f5c61f/eclipse-workspace/NoteTaker'
                }
        }
    stage("Build Application"){
            steps {
                sh "mvn clean package"
            }
       }
    stage("Test Application"){
           steps {
                 sh "mvn test"
           }
       }
    

  }
}
